### ISSUE TITLE
enhanchement 

### ISSUE THREAD

**Issue by Keertijanm** [Keertijanm/DSA-LinkedList-Java#13]
enhanchement needed

**Comment by SmartFasterTechi** [comment]
ok so in this we can provide a new medium level leetcode q.s

**Comment by Keertijanm** [comment]
ok we can rename file on the new q.s name

**Comment by SmartFasterTechi** [comment]
yes , Merge two unsorted linkelidt in to sorted linkedlist

**Comment by Keertijanm** [comment]
ok
